# (c) Copyright 2013 Carnegie Mellon University
# @author Andrew Hundt <ATHundt@gmail.com>

set(CMAKE_MESH_MAJOR_VERSION 0)
set(CMAKE_MESH_MINOR_VERSION 2)
set(CMAKE_MESH_PATCH_VERSION 0)
set(CMAKE_MESH_VERSION  ${CMAKE_MESH_MAJOR_VERSION}.${CMAKE_MESH_MINOR_VERSION}.${CMAKE_MESH_PATCH_VERSION})
set(PACKAGE_VERSION ${CMAKE_MESH_VERSION})

# Check whether the requested PACKAGE_FIND_VERSION is compatible
if("${PACKAGE_VERSION}" VERSION_LESS "${PACKAGE_FIND_VERSION}")
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if ("${PACKAGE_VERSION}" VERSION_EQUAL "${PACKAGE_FIND_VERSION}")
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
